bin = @["main"]
binDir = "target"
srcDir = "src"

requires "nim >= 1.2.0"
requires "glm >= 1.1.1"
requires "nimgl >= 1.1.0"
requires "patty >= 0.3.3"
requires "metric >= 0.1.0"
requires "typography >= 0.3.0"
requires "regex >= 0.15.0"
requires "chroma >= 0.1.0"
requires "perlin >= 0.6.1"
requires "metrics >= 0.0.1"
requires "astar >= 0.6.0"
requires "nimclipboard >= 0.1.2"